version: '3.4'
services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    volumes:
      - ./azurite/data:/data
    command: "azurite --blobHost 0.0.0.0 --tableHost 0.0.0.0 --queueHost 0.0.0.0 -d /data/debug.log -l /data"
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
