# version: '3.4'
services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    volumes:
      - ./apps/azurite/data:/data
    command: "azurite --blobHost 0.0.0.0 --tableHost 0.0.0.0 --queueHost 0.0.0.0 -d /data/debug.log -l /data"
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"

  og-incident-images:
    build:
      context: ./apps/og-incident-images/
      dockerfile: Dockerfile.dev
    cpu_count: 1
    mem_limit: 512m
    command: ["deno", "task", "dev"]
    develop:
      watch:
        - action: sync
          path: ./apps/og-incident-images/
          target: /app/
    ports:
      - "8080:80"
    depends_on:
      - azurite
    environment:
      INCIDENTS_API: https://lanco-live-incidents.azurewebsites.net/api/incidents
