// Generated by https://quicktype.io

namespace QuickType
{
    using System.Text.Json;
    using System.Text.Json.Serialization;

    public partial class Geocode
    {
        [JsonPropertyName("results")]
        public Result[] Results { get; set; }

        [JsonPropertyName("status")]
        public string Status { get; set; }
    }

    public partial class Result
    {
        [JsonPropertyName("address_components")]
        public AddressComponent[] AddressComponents { get; set; }

        [JsonPropertyName("formatted_address")]
        public string FormattedAddress { get; set; }

        [JsonPropertyName("geometry")]
        public Geometry Geometry { get; set; }

        [JsonPropertyName("place_id")]
        public string PlaceId { get; set; }

        [JsonPropertyName("types")]
        public string[] Types { get; set; }
    }

    public partial class AddressComponent
    {
        [JsonPropertyName("long_name")]
        public string LongName { get; set; }

        [JsonPropertyName("short_name")]
        public string ShortName { get; set; }

        [JsonPropertyName("types")]
        public string[] Types { get; set; }
    }

    public partial class Geometry
    {
        [JsonPropertyName("location")]
        public Location Location { get; set; }

        [JsonPropertyName("location_type")]
        public string LocationType { get; set; }

        [JsonPropertyName("viewport")]
        public Viewport Viewport { get; set; }
    }

    public partial class Location
    {
        [JsonPropertyName("lat")]
        public double Lat { get; set; }

        [JsonPropertyName("lng")]
        public double Lng { get; set; }
    }

    public partial class Viewport
    {
        [JsonPropertyName("northeast")]
        public Location Northeast { get; set; }

        [JsonPropertyName("southwest")]
        public Location Southwest { get; set; }
    }

    public partial class Geocode
    {
        public static Geocode FromJson(string json) => JsonSerializer.Deserialize<Geocode>(json);
    }

    public static class Serialize
    {
        public static string ToJson(this Geocode self) => JsonSerializer.Serialize(self);
    }
}
