FROM mcr.microsoft.com/azure-functions/dotnet:4-appservice

RUN curl -fsSL https://deno.land/x/install/install.sh | sh
ENV PATH="/home/.deno/bin:$PATH"

ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true

COPY host.dev.json /home/site/wwwroot/host.json
COPY og-images/function.json /home/site/wwwroot/og-images/function.json

WORKDIR /app

# These steps will be re-run upon each file change in your working directory:
COPY . .

# Compile the main app so that it doesn't need to be compiled each startup/entry.
RUN deno cache main.ts
